# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bba4d70bba181fb96b91b7d146283ec4e53ed437e1b32c2f6c3d1b84466a264635687e6267a045e27cc6ca392d8b494e4b206494acb6761e65f5454010fce40

test:
  secret_key_base: 2cdf8dd740365f6bd9d3bc1e852a84247ea6bbb366da7ecfc4d2342dcbaa391f41932cd7ada0ce4e444ef3075f3619a94ac1db93e0a518d0e440672d46c2f7c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
